import CaseEnum from '../../enums/case.enum';
import {FlagsToolInterface} from '../../interfaces/tools/flags.tool.interface';

export const CaseToolConst: { [key in keyof typeof CaseEnum]: FlagsToolInterface } = {
  Model: {
    method: false,
    model: true,
    all: false,
    not: false,
    connection: false,
  },
  Method: {
    method: true,
    model: false,
    all: false,
    not: false,
    connection: false,
  },
  AfterWrapperAndMethod: {
    method: true,
    model: false,
    all: false,
    not: true,
    connection: false,
  },
  BeforeWrapperAndMethod: {
    method: true,
    model: false,
    all: true,
    not: false,
    connection: false,
  },
  BeforeAndAfterWrapperAndMethod: {
    method: true,
    model: false,
    all: true,
    not: true,
    connection: false,
  },
  BeforeWrapperAndModel: {
    method: false,
    model: true,
    all: true,
    not: false,
    connection: false,
  },
  AfterWrapperAndModel: {
    method: false,
    model: true,
    all: false,
    not: true,
    connection: false,
  },
  BeforeAndAfterWrapperAndModel: {
    method: false,
    model: true,
    all: true,
    not: true,
    connection: false,
  },
  BeforeAndConnectionAndAfterWrapperAndMethod: {
    method: true,
    model: false,
    all: true,
    not: true,
    connection: true,
  },
  BeforeAndConnectionWrapperAndMethod: {
    method: true,
    model: false,
    all: true,
    not: false,
    connection: true,
  },
  ConnectionAndAfterWrapperAndMethod: {
    method: true,
    model: false,
    all: false,
    not: true,
    connection: true,
  },
  ConnectionWrapperAndMethod: {
    method: true,
    model: false,
    all: false,
    not: false,
    connection: true,
  },
  ConnectionWrapperAndModel: {
    method: false,
    model: true,
    all: false,
    not: false,
    connection: true,
  },
  BeforeAndConnectionAndAfterWrapperAndModel: {
    method: false,
    model: true,
    all: true,
    not: true,
    connection: true,
  },
  ConnectionAndAfterWrapperAndModel: {
    method: false,
    model: true,
    all: false,
    not: true,
    connection: true,
  },
  BeforeAndConnectionWrapperAndModel: {
    method: false,
    model: true,
    all: true,
    not: false,
    connection: true,
  },
};
