"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.CaseToolEnum = void 0;
var CaseToolEnum;
(function (CaseToolEnum) {
    CaseToolEnum[CaseToolEnum["Model"] = 0] = "Model";
    CaseToolEnum[CaseToolEnum["Method"] = 1] = "Method";
    CaseToolEnum[CaseToolEnum["AfterWrapperAndMethod"] = 2] = "AfterWrapperAndMethod";
    CaseToolEnum[CaseToolEnum["BeforeWrapperAndMethod"] = 3] = "BeforeWrapperAndMethod";
    CaseToolEnum[CaseToolEnum["BeforeAndAfterWrapperAndMethod"] = 4] = "BeforeAndAfterWrapperAndMethod";
    CaseToolEnum[CaseToolEnum["BeforeWrapperAndModel"] = 5] = "BeforeWrapperAndModel";
    CaseToolEnum[CaseToolEnum["AfterWrapperAndModel"] = 6] = "AfterWrapperAndModel";
    CaseToolEnum[CaseToolEnum["BeforeAndAfterWrapperAndModel"] = 7] = "BeforeAndAfterWrapperAndModel";
    CaseToolEnum[CaseToolEnum["ConnectionWrapperAndMethod"] = 8] = "ConnectionWrapperAndMethod";
    CaseToolEnum[CaseToolEnum["BeforeAndConnectionWrapperAndMethod"] = 9] = "BeforeAndConnectionWrapperAndMethod";
    CaseToolEnum[CaseToolEnum["ConnectionAndAfterWrapperAndMethod"] = 10] = "ConnectionAndAfterWrapperAndMethod";
    CaseToolEnum[CaseToolEnum["BeforeAndConnectionAndAfterWrapperAndMethod"] = 11] = "BeforeAndConnectionAndAfterWrapperAndMethod";
    CaseToolEnum[CaseToolEnum["ConnectionWrapperAndModel"] = 12] = "ConnectionWrapperAndModel";
    CaseToolEnum[CaseToolEnum["ConnectionAndAfterWrapperAndModel"] = 13] = "ConnectionAndAfterWrapperAndModel";
    CaseToolEnum[CaseToolEnum["BeforeAndConnectionAndAfterWrapperAndModel"] = 14] = "BeforeAndConnectionAndAfterWrapperAndModel";
})(CaseToolEnum = exports.CaseToolEnum || (exports.CaseToolEnum = {}));
